### ISSUE TITLE
skytils

### ISSUE THREAD

**Issue by Irian3x3** [Qalcyo/EvergreenHUD#49]
**Describe the bug**
Mod does not work with skytils.

**To Reproduce**
1. Launch Minecraft with Skytils and EvergreenHUD in the mod folder 

**Expected behavior**
game to work

**Screenshots**
![](https://irian3x3.xyz/assets/Screen%20Shot%202021-09-09%20at%206.43.09%20PM.png)

**EvergreenHUD Info:**
 - Mod Version: 2.0.0.69-pre.12
 - Minecraft Version: 1.8.9

**Comment by Deftu** [comment]
Download the latest version from https://modrinth.com

**Comment by Irian3x3** [comment]
i downloaded it from the latest pre-release, but ok

**Comment by Deftu** [comment]
> i downloaded it from the latest pre-release, but ok

The latest GitHub pre-release is outdated, the Modrinth version is the most recent pre-release.

**Comment by PumpkinXD** [comment]
the most recent release and pre-release broke again btw(not working with skytils 1.3pre4)

**Comment by Wyvest** [comment]
> the most recent release and pre-release broke again btw(not working with skytils 1.3pre4)

go to https://discord.gg/ztZusaNR3z for support

**Comment by Irian3x3** [comment]
> the most recent release and pre-release broke again btw(not working with skytils 1.3pre4)

year old issue + i don't use this mod anymore
